spring:
  cloud:
    stream:
      bindings:
        order-input-channel:
          destination: user
        takeaway-output-channel:
          destination: takeaway
        homedelivery-output-channel:
          destination: home
      kafka:
        streams:
          binder:
             brokers: localhost:9092